services:
  traefik:
    image: traefik:v3.5.0
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - shared-network
    ports:
      - "${HTTP_PROXY_PORT}:${HTTP_PROXY_PORT}"
      # - "${HTTPS_PROXY_PORT}:${HTTPS_PROXY_PORT}"
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/dynamic:/etc/traefik/dynamic:ro
      - ./data/acme:/acme:rw
      - ./data/log:/var/log:rw
    # environment:
    #   TENCENTCLOUD_SECRET_ID: ${TENCENTCLOUD_SECRET_ID}
    #   TENCENTCLOUD_SECRET_KEY: ${TENCENTCLOUD_SECRET_KEY}
    command:
      # EntryPoints
      - "--entrypoints.web.address=:${HTTP_PROXY_PORT}"
      # - "--entrypoints.websecure.address=:${HTTPS_PROXY_PORT}"
      # - "--entrypoints.websecure.http.tls=true"
      
      # 开启ping探活
      - "--ping=true"
      - "--ping.entrypoint=web"
      
      # Providers 
      # 启用 Docker 作为服务发现提供者
      - "--providers.docker=true"
      # 默认情况下不暴露容器,只有显式打上 Traefik 标签的容器才会被代理
      - "--providers.docker.exposedbydefault=false"
      # 指定 Traefik 使用 shared-network 网络与容器通信
      - "--providers.docker.network=shared-network"
      # 启用文件服务发现提供者
      - "--providers.file.watch=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      
      # API & Dashboard 
      # 启用 Traefik 内置的 Web 控制台
      - "--api.dashboard=true"
      # 必须通过受保护的入口点访问控制台
      - "--api.insecure=true"
      
      # Acme
      # - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      # - "--certificatesresolvers.letsencrypt.acme.storage=/acme/letsencrypt.json"
      # - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      # - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=${ACME_DNS_PROVIDER}"
      # - "--certificatesresolvers.letsencrypt.acme.dnschallenge.delaybeforecheck=5s"
      
      # Logging
      - "--log.level=INFO"
      - "--log.filePath=/var/log/traefik.log"
      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${CONTAINER_NAME}.service=api@internal"
      - "traefik.http.routers.${CONTAINER_NAME}.rule=Host(`${CONTAINER_NAME}.${APP_BASE_DOMAIN}`)"
      - "traefik.http.routers.${CONTAINER_NAME}.entrypoints=web"
      # - "traefik.http.routers.${CONTAINER_NAME}.entrypoints=websecure"
      # - "traefik.http.routers.${CONTAINER_NAME}.tls=true"
      # - "traefik.http.routers.${CONTAINER_NAME}.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.${CONTAINER_NAME}.tls.domains[0].main=*.${APP_BASE_DOMAIN}"
      - "traefik.http.routers.${CONTAINER_NAME}.middlewares=basic-auth@file"

      # 探活
      - "traefik.http.routers.ping.service=api@internal"
      - "traefik.http.routers.ping.rule=Host(`ping.${APP_BASE_DOMAIN}`) && Path(`/ping`)"
      - "traefik.http.routers.ping.entrypoints=web"
      # - "traefik.http.routers.ping.entrypoints=websecure"
      # - "traefik.http.routers.ping.tls=true"
      # - "traefik.http.routers.ping.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.ping.tls.domains[0].main=*.${APP_BASE_DOMAIN}"
      - "traefik.http.routers.ping.middlewares=ping-cors"
      - "traefik.http.middlewares.ping-cors.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.ping-cors.headers.accessControlAllowMethods=GET,POST,OPTIONS,HEAD"
      - "traefik.http.middlewares.ping-cors.headers.accessControlAllowHeaders=*"
      - "traefik.http.middlewares.ping-cors.headers.customResponseHeaders.Cache-Control=no-store, no-cache, must-revalidate"
      - "traefik.http.middlewares.ping-cors.headers.customResponseHeaders.Pragma=no-cache"
networks:
  shared-network:
    external: true